TITLE="^#  *((?:[,. ]*\\w+)+)[,. ]*(?:[-=]?> *((?:,? *(?:\\w+:)? *\\w+)+))? *"
ACCESS="^(?:share|access): *((?: *,? *\\w+  *(?:r|w|read|write))+) *$"
PROQUINT="(?:_?[aioubdfghjklmnprstvz]{5})+"
USERNAME="^[a-z0-9_]{3,10}$"
PASSWORD="^.{6,64}$"