TITLE="^#  *((?:[,. ]*\\w+)+)[,. ]*(?:[-=]?> *((?:,? *(?:\\w+:)? *\\w+)+))? *"
ACCESS="^(?:share|access): *((?: *,? *\\w+  *(?:r|w|read|write))+) *$"
PROQUINT="(?:_?[aioubdfghjklmnprstvz]{5})+"
USER="^[a-z0-9_]+$"